server.port: 9966
spring.profiles: default
demo.security.jwt:
  tokenExpirationTime: 15 # Number of minutes
  refreshTokenExpTime: 60 # Minutes
  tokenIssuer: http://br.com.velhoamigo
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus

spring.datasource:
  url: ${JDBC_DATABASE_URL}
  username: ${JDBC_DATABASE_USERNAME}
  password: ${JDBC_DATABASE_PASSWORD}
  driver-class-name: com.mysql.jdbc.Driver
  data: "classpath*:data.sql"

spring.jpa:
  database: MYSQL 
  hibernate.ddl-auto: create-drop 
